[config]
schemaVersion = "0.0.1"


[package]
namespace = "ThePotatoes"
name = "Hack_Away"
versionNumber = "0.0.1"
description = "Rehauls the axe weapon. Makes QOL changes to the axe block special"
websiteUrl = "https://github.com/ThePotatomancer/HackAway-Hades2-mod"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.28"
SGG_Modding-ENVY = "1.0.1"
SGG_Modding-Chalk = "2.0.2"
SGG_Modding-ModUtil = "3.1.0"
SGG_Modding-ReLoad = "1.0.1"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
